
package com.abc.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Sun Sep 24 17:27:16 IST 2017
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "listPersons", namespace = "http://webservice.abc.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listPersons", namespace = "http://webservice.abc.com/")

public class ListPersons {


}

